### PR TITLE
Tick all the checkboxes under a category when select all lists is ticked

### PR DESCRIPTION
**Pull request by MatheusHamonangan**
Hi there, 

I've submitted an enhancement request in mantis https://mantis.phplist.com/view.php?id=17630, it has all the description there. Basically, I modified the phplist slighlty to suit my needs. I thought I might just share what I did and maybe it could help some people. Please let me know what do you think about the patch.

Thank you,

Matheus

### CODE REVIEW

**Comment by michield** [comment]
nice. What's not clear to me is what the "check-all" element is that needs to be clicked to activate it. Does it need translation?

**Comment by MatheusHamonangan** [comment]
Hi there,

Sorry I was away for the past 4 days. Yes, the check-all element needs to be ticked if user wants to check all lists in that category. I think the string will need to have translation so it can be used in any other language. 

Cheers,

Matheus

**Comment by michield** [comment]
but where is it ? The "check-all" element?

**Comment by MatheusHamonangan** [comment]
Hi there,

It's in here https://github.com/MatheusHamonangan/phplist3/commit/fc2bacaa56afe18ecd91433cce42611dae0d5cda, the phplist repo, not under phplist-dressprow.

**Comment by michield** [comment]
ah, ok, that explains. You'll need to PR that change. Could you [sign the CLA](https://www.phplist.com/cla) when you do that?

**Comment by MatheusHamonangan** [comment]
Hi there,

I've already sent a pull-request for that change (https://github.com/phpList/phplist3/pull/6). Yep, I can sign the CLA.

Cheers,

Matheus

**Comment by MatheusHamonangan** [comment]
Hi there,

Since I am contributing on behalf of a company (Catalyst Ltd), the CLA is being reviewed by the legal department, but It shouldn't be a problem.


Thank you,


Matheus

**Comment by michield** [comment]
any update from your legal dept?

**Comment by MatheusHamonangan** [comment]
Hi there,

Sorry it took longer than expected. I am still waiting for an answer from
the legal department, and I think it will take quite some time for them to
give an exact answer for this. Sorry about that.


Thanks,


Matheus

**Pull request merged**
