### PR TITLE
Added comments; Removed some unnecessary conditional statements

### PR DESCRIPTION
**Pull request by samtuke**

### CODE REVIEW

**Comment by michield** [comment]
https://mantis.phplist.org/view.php?id=18128

**Comment by bramley** [comment]
I don't think that these changes are addressing Mantis 18128. Probably best to include any tidying-up of the code with addressing that problem rather than as a separate change.

**Comment by samtuke** [comment]
Indeed this PR does not affect the referenced mantis issue, though I was pursuing that issue when I made the changes in these commits.

I found the Onyx RSS code slow to work with and could not come to any conclusions during the time that I spent.

These commits are simply code commenting and tidying and should not affect application behaviour.

**Comment by bramley** [comment]
Merging this PR is going to make merging my one more difficult as there are likely to be conflicts.

Can I suggest to be a bit more fussy in applying pull requests? Maybe have a discussion on what has been proposed and whether it is needed before merging.

I think that commenting individual lines should generally be avoided, only when something is really unclear. As an example, I don't think that this adds anything

```
// Set the counter to zero
$count = 0;
```

**Comment by michield** [comment]
Yes, I agree. Sorry, I only realised that I was unable to merge the other PR after accepting this one. I will revert this one, as it has less addition than yours.

**Comment by michield** [comment]
Hmm, reverting is not trivial. Any chance you can pull and re-submit your PR?

**Comment by michield** [comment]
Actually, it's fine. I'll fetch it from https://raw.githubusercontent.com/bramley/phplist-ui-dressprow/3cf9f1981a08953b28881d2516f1578ed88fde50/rssfeed.php

**Comment by samtuke** [comment]
@bramley Good points, it would have been better if I had checked out your branch and made my changes there instead (to avoid conflicts).

**Pull request merged**
